# Generated by Django 5.2.9 on 2025-12-21 09:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramRegisterToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('chat_id', models.CharField(blank=True, max_length=32)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='access',
            name='pak_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='access',
            name='ssh_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
