# Generated by Django 5.2.9 on 2025-12-22 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0004_telegramregistertoken_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='access',
            unique_together={('user', 'vm')},
        ),
        migrations.CreateModel(
            name='VmUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Логин обычного пользователя (вводится вручную)', max_length=64)),
                ('password8', models.CharField(help_text='8-значный пароль (вводится вручную)', max_length=8)),
                ('ssh_private_key', models.TextField(blank=True, null=True)),
                ('ssh_public_key', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(help_text='Менеджер (Django user), который создал этого обычного пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='created_vm_users', to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_users', to='vm_app.virtualmachine')),
            ],
            options={
                'db_table': 'VmUser',
                'indexes': [models.Index(fields=['vm', 'username'], name='VmUser_vm_id_e1591d_idx'), models.Index(fields=['manager'], name='VmUser_manager_181060_idx')],
                'unique_together': {('vm', 'username')},
            },
        ),
    ]
