# Generated by Django 5.2.9 on 2025-12-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0005_alter_access_unique_together_vmuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twofa_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'SiteSettings',
            },
        ),
    ]
