# Generated by Django 5.2.9 on 2025-12-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0006_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmuser',
            name='password8',
            field=models.TextField(),
        ),
    ]
